Student view perf dn
OC-ComputerScience/performancescheduling-backend pull request #19
Opened 2023-07-28 02:49 UTC by dbnorth

Need to use the student-view-perf-dn fronted  to test

2023-08-07 02:44 UTC, AndrewClubb requested changes

2023-08-07 02:44 UTC, AndrewClubb commented on app/controllers/studentInstrument.controller.js
> +  console.log("***********************", req.query.date);
Remove this

2023-08-13 22:02 UTC, dbnorth commented on app/controllers/studentInstrument.controller.js
> +  console.log("***********************", req.query.date);
done

2023-08-13 22:03 UTC, AndrewClubb approved these changes

2023-08-13 22:03 UTC, merged